### ISSUE TITLE
"receive" function from solidity 0.6.2+ does not decode

### ISSUE THREAD

**Issue by WyseNynja** [rust-ethereum/ethabi#185] opened 2020-04-01 04:08 UTC
```
thread 'main' panicked at 'failed to load contract at ../../contracts/abi/MyKollateralInvokable.json: SerdeJson(Error("Invalid operation type", line: 298, column: 3))', src/order/contracts.rs:54:9
```

I tweaked the error message to print out the type and it was "receive".

We need to add it to operation.rs

**Comment by adoerr** [comment] 2020-05-07 12:14
Could that be a duplicate of #187 ?
BTW, any plans for a release including #187 soon?

**Comment by bryanapperson** [comment] 2021-05-22 20:31
I am still seeing this in ethabi 14.0.0:

```
  {
    "stateMutability": "payable",
    "type": "receive"
  }
 ```
 In a contract, like for example the set token contract, will trigger.

**Comment by taminomara** [comment] 2021-06-23 14:59
@bryanapperson I can't reproduce it, are you sure you're on `14.0.0`?

**Comment by taminomara** [comment] 2021-06-23 15:08
I've tried it with https://bscscan.com/address/0x1b391f9d0fffa86a6088a73ac4ac28d12c9ccfbd#code.

**Comment by taminomara** [comment] 2021-06-25 16:36
@vkgnosis @nlordell given that there are tests with `receive` function in `ethcontract-rs` and they work just fine, I propose closing this.

**Closed** 2021-06-28 13:57 UTC

**Comment by bryanapperson** [comment] 2021-06-28 15:38
Yup, it ended up that this change was not included in the library I was using, thanks for the follow up.
